### ISSUE TITLE
Import & Export Feature In Address

### ISSUE THREAD

**Issue by niyajali** [skniyajali/PoposRoom#243]
**Is your feature request related to a problem? Please describe.**
Add new feature into address for importing and exporting data to file

## Todo's

- [ ] Create a new package called settings
- [ ] Create an Import Screen for importing data from the file
- [ ] Create an Export Screen for exporting data to a file
- [ ] Create an Event class for all actions
- [ ] Create a ViewModel for managing the screen actions
- [ ] Create a repository method for importing data to the database
- [ ] Connect with the database and apply the logic
- [ ] Connect with existing feature
