### ISSUE TITLE
Feature Req - Daily Market List

### ISSUE THREAD

**Issue by niyajali** [skniyajali/PoposRoom#329]
**Is your feature request related to a problem? Please describe.**
Develop a new feature that helps users add and share a daily market list

## Todo's

- [ ] Add a new feature inside of market item to allow the user to add market items to their daily bucket list
- [ ] Create a screen to add items to the bucket list on a specific date
- [ ] Create a screen to update items on the bucket list on a specific date
- [ ] Create an event class for managing screen events
- [ ] Create  a ViewModel class to perform all screen events
- [ ] Create a table in the database for managing data
- [ ] Create a Model for managing data
- [ ] Create a Dao interface for managing data into the database
- [ ] Create a Repository Interface for managing events and data
- [ ] Create a Repository Implementation for implementing and managing all events and data
