### ISSUE TITLE
Feature Req - Notification

### ISSUE THREAD

**Issue by niyajali** [skniyajali/PoposRoom#380]
**Is your feature request related to a problem? Please describe.**
Create a new package notification for sending app notification

## Todo's

- [ ] Create a notifications package inside of  **:core** package
- [ ] Create a Notifier Interface for different types of notification
- [ ] Create a Notifier Implementation for notifier methods
- [ ] Create a Notifier Module for DI
- [ ] Create a DataDeletetion Worker Notification
- [ ] Create a ReportGeneration Worker Notification
- [ ] Write test classes for testing notification
