### ISSUE TITLE
Enhancement - Account

### ISSUE THREAD

**Issue by niyajali** [skniyajali/PoposRoom#421]
**Is your feature request related to a problem? Please describe.**
Enhance Features, fix issues, and improve performance

## Todo's

- [ ] Search bar will only be visible when some items are available
- [ ] Change AddEditAdress Destination to BottomSheet Destination
- [ ] Change AdressSettings Destination to BottomSheet Destination
- [ ] Show proper message when creating or updating address
- [ ] Write Unit test for this feature
- [ ] Write UI/Instrumented test for this feature
