### ISSUE TITLE
Enhancement - DailyMarket

### ISSUE THREAD

**Issue by niyajali** [skniyajali/PoposRoom#472]
**Is your feature request related to a problem? Please describe.**
Enhance Features, fix issues, and improve performance

## Todo's

- [ ] Search bar will only be visible when some items are available
- [ ] Change DailyMarketSettings Destination to BottomSheet Destination
- [ ] Show proper message when creating or updating address
- [ ] Trim text to an end when some input is given in the text field
- [ ] Capitalize words when creating or updating data
- [ ] Fix Back Handler Issue
- [ ] Fix bottom bar issue on showing on empty export screen
- [ ] Write Unit test for this feature
- [ ] Write UI/Instrumented test for this feature
